config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about' => 'pages#about'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<%= nav_bar fixed: :top, brand: "Fashionable Clicheizr 2.0", responsive: true do %>
    <%= menu_group do %>
        <%= menu_item "Home", root_path %>
        <%= menu_divider %>
        <%= drop_down "Products" do %>
            <%= menu_item "Things you can't afford", "#" %>
            <%= menu_item "Things that won't suit you anyway", "#" %>
            <%= menu_item "Things you're not even cool enough to buy anyway", "#" %>

                <%= menu_item "Bikes", "#" %>

        <% end %>
        <%= menu_item "About Us", about_path %>
        <%= menu_item "Contact", "#" %>
    <% end %>
    <%= menu_group pull: :right do %>

            <%= menu_item "Log Out", "#" %>



        <% end %>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>this is about us</p>

app/views/pages/home.html.erb
<h1>Welcome to my app</h1>
<p>About us <%= link_to 'here', about_path %>.</p>
<%= badge(12, :warning) %>
  